### PR TITLE
Adding Firebase Emulator Suite Support in Firestore

### PR DESCRIPTION
**Pull request by danilomartins18**
I saw the possibility to add support to Firebase Emulator Suite for Firestore. I don't know if there's a better way to do this, but if you find it interesting, please check it out.

Detail: It's my first pull request through a fork, so be kind :) lol

### CODE REVIEW

**Comment by aguacongas** [comment]
@danilomartins18 thanks to contribute, I really appreciate.

**Comment by danilomartins18** [comment]
@aguacongas It is an honor to contribute to this project.

No problems about the appveyor.

Of course, I just commited the unit tests, please check it out if it is enough.

**Comment by aguacongas** [comment]
@danilomartins18 It's ok for unit tests but please update your code as expected in the review

**Comment by danilomartins18** [comment]
What do you mean about update the code as expected in the review?

**Comment by aguacongas** [comment]
@danilomartins18  I reviewed your code and wrote comments . please fix `UseEmulator` private method at line 179 of *IdentityBuilderExtensions.cs* by removing conditional compilation directive.

**Comment by danilomartins18** [comment]
Okay, sorry but your comment review doesn't display for me. I removed the conditional compilation directive, please check it out.

**Pull request merged**
